### ISSUE TITLE
The fix for "Open all in tabs" added an unwanted "close tab" button

### ISSUE THREAD

**Issue by N1mu3h** [onemen/TabMixPlus#278] opened 2024-03-10 15:00 UTC
While [this](https://github.com/onemen/TabMixPlus/issues/275#issuecomment-1986963936_) DID indeed fix the initial issue it added a [close tab button](https://i.imgur.com/yFGGs93.jpg) all the way on the right of the Tab Bar that wasn't there before.

If I go to TMP Settings - Display - Tab Bar and tick "Close tab button", then Apply, UNtick it again and Apply then that button/x is gone. But it returns every time I restart the browser.

I'm hoping that's a quick + easy fix again too 🤞🏼🙂

**Comment by onemen** [comment] 2024-03-10 19:57
![button](https://github.com/onemen/TabMixPlus/assets/3650909/363301b5-d2cc-4789-b849-be084edd93d3)

Do you mean this checkbox is checked after restart ?

**Comment by N1mu3h** [comment] 2024-03-10 20:01
No it's not checked, but the X is there after a restart. I've never had it checked, so no idea where that X suddenly came from.
I have to check that box, hit apply, then UNcheck and apply again for the X to go away ... until the next Waterfox restart 🤷🏼‍♀️

**Comment by onemen** [comment] 2024-03-10 21:14
check if you see any messages in the `Browser Console`

**Comment by N1mu3h** [comment] 2024-03-10 21:35
I shows [some errors](https://i.imgur.com/15lNRWR.jpg) (in my regular profile), but nothing I can decipher. I'm on Win10 btw.
I'll look into creating a new profile tomorrow, not sure how to do that though. It's late now, I'll google it tomorrow - unless the errors in the screenshot already tell you what's up.
Thanks again 🙂

**Comment by onemen** [comment] 2024-03-10 22:01
Post a file with your Tab Mix Plus preferences

**Comment by N1mu3h** [comment] 2024-03-10 22:40
Wow that's interesting: The X was still there when I opened the browser and TMP Preferences. But as soon as I clicked on "Export Preferences" the X all the way on the right side was gone.

Well here are the exported TMP preferences and a new screenshot ... and now off to bed 😉

[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/14551997/TMPpref.txt)

![Capture](https://github.com/onemen/TabMixPlus/assets/33838834/a780076c-84ab-4607-a2df-4b3de7e65870)

**Comment by 117649** [comment] 2024-03-11 06:05
![image](https://github.com/onemen/TabMixPlus/assets/8281345/f9496a00-b2be-412a-95ce-d3ee8ecc34e8)
Can confirm when browser is newly start the setting is not in function. 
Have to some how prime it for it to working.

**Comment by onemen** [comment] 2024-03-11 06:27
@117649,

Do you see the same errors in Browser Console?

I can not reproduce it on Windows 11 with latest WaterFox

In @N1mu3h post there are some messages from `ChromeUtils.jsm` about `ChromeUtils.defineESModuleGetters`

Can you modify this lines in `ChromeUtils.jsm` and check if you see more information about the error

```diff
      if (Object.keys(esModules).length) {
+       try {
          ChromeUtils.defineESModuleGetters(lazy, esModules);
+       } catch (error) {
+         console.log(error);
+       }
      }
```

**Comment by N1mu3h** [comment] 2024-03-11 06:51
I can't find ChromeUtils.jsm in my Chrome folder or anywhere on my boot drive - where is it supposed to be? Nor is ChromeUtils mentioned in userChrome.css or simpleMenuWizard.css, so I have no idea what to do with those lines.

Also neither Services.appinfo.name nor Services.appinfo.version show anything - you did mean if I enter it under "Filter Output", right?

**Comment by 117649** [comment] 2024-03-11 07:35
![image](https://github.com/onemen/TabMixPlus/assets/8281345/a5dac563-847f-40d5-b075-7d6c82143a0f)
Looks like some how window.lazy is not been initiated here.

**Comment by onemen** [comment] 2024-03-11 07:41
@117649 

```diff
      if (Object.keys(esModules).length) {
+       try {
          ChromeUtils.defineESModuleGetters(lazy, esModules);
+       } catch (error) {
+         console.log('Error when Tabmix call ChromeUtils.defineESModuleGetters with', esModules);
+         console.log(error);
+       }
      }
```

can you add `console.log('Error when Tabmix call ChromeUtils.defineESModuleGetters with', esModules);`  and post the result

@N1mu3h 

`ChromeUtils.jsm` is part of Tab Mix Plus, is inside the .xpi file which is simple zip file

**Comment by N1mu3h** [comment] 2024-03-11 08:04
Now I found it lol. Attached is the whole log after restarting Waterfox ... I hope it helps 🙂

[console-export-2024-3-11_9-2-57.txt](https://github.com/onemen/TabMixPlus/files/14555271/console-export-2024-3-11_9-2-57.txt)

**Comment by onemen** [comment] 2024-03-11 08:16
Download this [test build](https://github.com/onemen/TabMixPlus/files/14555412/test-build-1.19.1-pre.20240311.1.zip) zip file

Change its extension from `.zip` to `.xpi` and install it

**Comment by N1mu3h** [comment] 2024-03-11 08:26
Yesssss, the evil X no longer shows up when restarting Waterfox!

Thanks again, you've been rockstar these last few days 🥰

Should I close this issue too or do you need further feedback?

**Comment by onemen** [comment] 2024-03-11 08:34
@N1mu3h , @117649  Thank you for your help

I will close this issue once I upload the new dev-build

**Closed** 2024-03-11 08:54 UTC
