### ISSUE TITLE
Restart prompt

### ISSUE THREAD

**Issue by Tanookirby** [onemen/TabMixPlus#125] opened 2022-03-19 17:45 UTC
Since I installed the pre6 version of TabMixPlus, I keep getting the alert to restart Firefox every time I open the browser. What do you suggest I do to stop it from occurring?

**Comment by onemen** [comment] 2022-03-19 17:52
try this:

1. remove Tab mix.
2. Open about:support and click "Clear startup cache…" to restart Firefox
3. After Firefox starts close it again to make sure cache was clean.
4. Start Firefox
5. Install Tabmix

**Comment by cxen** [comment] 2022-03-21 10:11
> try this:
> 
>     1. remove Tab mix.
> 
>     2. Open about:support and click "Clear startup cache…" to restart Firefox
> 
>     3. After Firefox starts close it again to make sure cache was clean.
> 
>     4. Start Firefox
> 
>     5. Install Tabmix

I tried this and the prompt still appears every time.

**Comment by onemen** [comment] 2022-03-21 13:16
@117649 , do you think this is an issue with our `bootstrap.js` or maybe `BootstrapLoader.jsm`?

**Comment by cxen** [comment] 2022-03-21 15:46
> @cxen Can you try install with a clean profile?

I downloaded a fresh Firefox portable (98.0.1), and installed firefox-scripts and TMP [1.0.0-pre.6 (2022-03-12)]. The restart prompt always appears.

**Comment by onemen** [comment] 2022-03-21 19:10
post a link to Firefox portable (98.0.1), i will test it on my pc

**Comment by onemen** [comment] 2022-03-22 08:19
@cxen, I can't reproduce this issue

what is the date of the file `BootstrapLoader.jsm`, `[YORE_PROFILE]/chrome/utils`

try this again https://github.com/onemen/TabMixPlus/issues/125#issuecomment-1073714835

but in step 8, make sure to download Tab mix before installing it.
- Download [latest Tab mix](https://github.com/onemen/TabMixPlus/releases) to your local machine
- Open about:addons and click the cog icon to open the `tools for all add-ons`
- Click on `Install Add-on From File...`
![install](https://user-images.githubusercontent.com/3650909/159187612-540f4967-4765-4e54-829c-6ca490a5fbd4.png)

**Comment by cxen** [comment] 2022-03-22 09:45
BootstrapLoader.jsm is 04-Feb-2022

I repeated the steps above and included your suggestion to "Install from file" instead of drag+drop (should be the same thing, right?)

Same result, unfortunately.

**Comment by onemen** [comment] 2022-03-22 09:48
what is your operating system?

**Comment by onemen** [comment] 2022-03-22 10:26
@xiaoxiaoflood, do you have any idea regarding this issue ?

**Comment by cxen** [comment] 2022-03-22 11:29
> what is your operating system?

Win10, 21H2, 19044.1586

**Comment by onemen** [comment] 2022-03-22 17:53
I've found a typo in the file install.rdf that was bundled in tab_mix_plus-dev-build.xpi

Download [latest Tab mix](https://github.com/onemen/TabMixPlus/releases) **AGAIN** to your local machine
and install Tab Mix from the new file

**Comment by cxen** [comment] 2022-03-22 22:06
Great! Seems to be fixed.

**Closed** 2022-03-23 04:32 UTC
