### ISSUE TITLE
"When closing a tab, other tabs should not resize until cursor leaves toolbar region" issue since v1.24.0 update

### ISSUE THREAD

**Issue by AuRiMaS666** [onemen/TabMixPlus#348] opened 2024-10-20 15:43 UTC
Hello,

Since updating to TMP v1.24.0, I've noticed that tabs don't align themselves correctly anymore in a way that the close button is directly under the mouse cursor to allow closure of multiple tabs in quick succession. See the examples below.

v1.23.0:

https://github.com/user-attachments/assets/ff18861e-8245-4670-83e8-58da8bba3c94

v1.24.0 and latest dev build:

https://github.com/user-attachments/assets/94ea6f85-f06d-4ac7-a79d-020e6b21b806

My TMP settings:

[TMPpref.txt](https://github.com/user-attachments/files/17450951/TMPpref.txt)

**Comment by pyrates999** [comment] 2024-10-20 22:57
Have you tried the dev version? https://github.com/onemen/TabMixPlus/releases/tag/dev-build

Open up the tab mix plus options and go to display -> tab and look for "tab width fills rows on overflow".

**Comment by AuRiMaS666** [comment] 2024-10-21 06:09
I am using that version and this option doesn't seem to make any difference at all.

**Comment by pyrates999** [comment] 2024-10-21 06:42
did you try unticking that option so it doesn't auto resize the tabs?

**Comment by AuRiMaS666** [comment] 2024-10-21 06:50
Sorry, forgot to mention that it doesn't seem to make any difference, on or off.

**Comment by pyrates999** [comment] 2024-10-21 07:06
the mechanism for resizing tabs might be happening right after you click a tab to close it.

**Comment by pyrates999** [comment] 2024-10-21 07:08
In your firefox user profile directory, create a directory named chrome and create a file named userChrome.css with the following:

`
/*add the following below for tab mix plus addon v1.24.1-2024-10-12 with option Tab width fills rows on overflow, enabled*/
#tabbrowser-tabs[orient="horizontal"][multibar]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab[fadein]:not([pinned]) .tab-background {
  max-width: var(--tabmix-tab-overflow-width, var(--tab-min-width)) !important;
}
`

**Comment by onemen** [comment] 2024-10-21 07:30
The issue started after this commit c0c8416cf12df17a293e08c26604e09383fed64a

I think the problem is with this:
```css
#tabbrowser-tabs[orient="horizontal"]:not([widthFitTitle]) > #tabbrowser-arrowscrollbox > .tabbrowser-tab:not([pinned]) {
  box-sizing: content-box;
}

```

**Comment by onemen** [comment] 2024-10-21 08:30
This test build should fix this issue

Download this [test-build](https://github.com/user-attachments/files/17457686/test-build-1.24.1-20241021.1126.zip)

Rename it to `.xpi`and install it.

Report back

**Comment by AuRiMaS666** [comment] 2024-10-21 09:51
All back to normal with this build.

Thank you for a quick resolution as always!

**Closed** 2024-10-21 11:08 UTC
