### ISSUE TITLE
wired misplace of reopened tab, can't always reproduce.

### ISSUE THREAD

**Issue by 117649** [onemen/TabMixPlus#175] opened 2022-10-30 14:05 UTC
Close a tab, open a new tab at several places away from its original place, then reopen that tab.
The tab will have a chance reopen at 1~2 places left or right of the place it should be which may correspond to the place of new tabs opened.
If reopen more then one tab they seems have the same drift distances.

Can't always trigger this. Not sure if this is a problem of TMP or caused by Firefox itself. 

[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/9896017/TMPpref.txt)

**Comment by onemen** [comment] 2022-10-31 15:32
@117649,

You have the option to restore position enabled.
So if the tab was in position 3 when you closed it, it suppose to be in position 3 when you restore it.

lets say you have tabs 12**3**456, and you close tab 3
- before closing 12**3**456
- after closing tab 3 12456
- now open new tabs and you have abcd12456
- restore tab 3 and you should get ab**3**cd12456


look at the code and check if something is wrong with it
https://github.com/onemen/TabMixPlus/blob/4783262bc3d5ab17b27df8dc1bf9b0c5757e7c6c/addon/chrome/content/session/sessionStore.js#L710-L722

**Comment by 117649** [comment] 2022-10-31 20:04
>     * before closing 12**3**456
> 
>     * after closing tab 3 12456
> 
>     * now open new tabs and you have abcd12456
> 
>     * restore tab 3 and you should get ab**3**cd1245

What I got isn't like that.

What I got is this:
before: 123456789
close 7: 12345689
open new: a12345689
reopen: a123457689
only 1 place drift from original.

Not always but some time:
open 2 new: ab12345689
reopen: ab123475689

open at other end: 12345689a
reopen:123456879a

And some time it not happen at all.

**Comment by 117649** [comment] 2022-10-31 20:35
@onemen I've just noticed that `_tPos` seems be re-calculated when ever changes made to tabs bar.
Why not apply the similar procedure to reopen-tabs queue?

**Comment by onemen** [comment] 2022-11-01 07:56
found it.

Download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.11.20221101.1.xpi). 

The `Object.assign` was a left over from changes I've made 5 yeas ago, but since 9b4a061 (16/08/2021), the restored tab state.index was override the value we set with `index: gBrowser.tabs.length`.
https://github.com/onemen/TabMixPlus/blob/4783262bc3d5ab17b27df8dc1bf9b0c5757e7c6c/addon/chrome/content/session/sessionStore.js#L682-L689

This is the patch
```diff
     let newTab = reuseExisting ? aBlankTabToReuse :
-      gBrowser.addTrustedTab(null, Object.assign({
+      gBrowser.addTrustedTab(null, {
         createLazyBrowser,
         skipAnimation: tabToRemove || skipAnimation,
         allowInheritPrincipal: true,
         noInitialLabel: true,
+        pinned: state.pinned,
         userContextId,
         index: gBrowser.tabs.length,
-      }, state));
+      });
```

**Comment by 117649** [comment] 2022-11-01 08:39
> found it.
> 
> Download and try this [test build](https://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.11.20221101.1.xpi).
> 
> The `Object.assign` was a left over from changes I've made 5 yeas ago, but since [9b4a061](https://github.com/onemen/TabMixPlus/commit/9b4a061b84d7460f641343ea65de5df2a18fef76) (16/08/2021), the restored tab state.index was override the value we set with `index: gBrowser.tabs.length`.
> 
> https://github.com/onemen/TabMixPlus/blob/4783262bc3d5ab17b27df8dc1bf9b0c5757e7c6c/addon/chrome/content/session/sessionStore.js#L682-L689
> 
> This is the patch
> 
> ```diff
>      let newTab = reuseExisting ? aBlankTabToReuse :
> -      gBrowser.addTrustedTab(null, Object.assign({
> +      gBrowser.addTrustedTab(null, {
>          createLazyBrowser,
>          skipAnimation: tabToRemove || skipAnimation,
>          allowInheritPrincipal: true,
>          noInitialLabel: true,
> +        pinned: state.pinned,
>          userContextId,
>          index: gBrowser.tabs.length,
> -      }, state));
> +      });
> ```

Unfortunately not seeing any effect.

And I don't think there should be any improvement if it just set `index: gBrowser.tabs.length` as we have saw `_tPos` is remapped for all tabs with every change.

**Comment by onemen** [comment] 2022-11-01 16:38
`_tPos` is just a getter to the the tab index.

try to clear cache
Open about:support and click "Clear startup cache…" to force Firefox to load userChromeJS on the next startup.

can you provide an exact steps to reproduce this issue.
provide info about the closed tab state (url, history etc...)

**Comment by 117649** [comment] 2022-11-01 16:57
> 

cache is cleared.

step to reproduce:

1: close a tab that is not at start or end of tab bar.

2:open new tabs(with 'open next to current one') at several places to the left of the original place of the closed tab.

3:reopen closed tab.

The tab reopened at several places left of the place it should be.

12345 --> 1235 --> ab1235 --> ab14235

**Comment by onemen** [comment] 2022-11-01 17:13
@117649 ,

That is how it suppose to work.

123**4**5 --> 1235 --> ab1235 --> ab1**4**235

tab 4 was in index 3 before you close it and it is in index 3 after you restored it.

**Comment by 117649** [comment] 2022-11-01 17:30
> @117649 ,
> 
> That is how it suppose to work.
> 
> 123**4**5 --> 1235 --> ab1235 --> ab1**4**235
> 
> tab 4 was in index 3 before you close it and it is in index 3 after you restored it.

......em

Consider to adding some mechanic to make index of the reopened count the offset?

**Comment by onemen** [comment] 2022-11-01 17:39
> Consider to add some mechanic to make index of the reopened count the offset?

How?

**Comment by 117649** [comment] 2022-11-01 18:00
> > Consider to add some mechanic to make index of the reopened count the offset?
> 
> How?

Add some monitor to edit tabs in reopen queue?

**Comment by onemen** [comment] 2022-11-01 18:57
You can suggest a PR

**Closed** 2022-11-02 05:36 UTC
